version: "3"

services:
  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - '../nginx/nginx.conf:/etc/nginx/nginx.conf'
    ports:
      - 80:80
    restart: always
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    volumes:
      - ../db/conf.d:/etc/mysql/conf.d
#      - ../db/data:/var/lib/mysql
      - ../db/initdb.d:/docker-entrypoint-initdb.d
    env_file: ../db/.env
    environment:
      TZ: Asia/Seoul
    restart: always
  backend:
    build:
      context: ../../backend/
      dockerfile: Dockerfile
    container_name: whatsup_backend
#    environment:
    ports:
      - "8080:8080"
    command: ['java', '-jar', 'app.jar']
#    volumes:
#      - ../../backend/:/backend
#    restart: unless-stopped
